//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourDeep.Dizzle.CustomCode.CodeGeneration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeGenerationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeGenerationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourDeep.Dizzle.CustomCode.CodeGeneration.CodeGenerationResource", typeof(CodeGenerationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AggregateInterfaces {
            get {
                object obj = ResourceManager.GetObject("AggregateInterfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AggregateRoot {
            get {
                object obj = ResourceManager.GetObject("AggregateRoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AggregateRootCoreTemplate {
            get {
                object obj = ResourceManager.GetObject("AggregateRootCoreTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AggregateState {
            get {
                object obj = ResourceManager.GetObject("AggregateState", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Commands {
            get {
                object obj = ResourceManager.GetObject("Commands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CopyrightHeader {
            get {
                object obj = ResourceManager.GetObject("CopyrightHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DomainNamespaces {
            get {
                object obj = ResourceManager.GetObject("DomainNamespaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Entities {
            get {
                object obj = ResourceManager.GetObject("Entities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Events {
            get {
                object obj = ResourceManager.GetObject("Events", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Views {
            get {
                object obj = ResourceManager.GetObject("Views", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
