//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace FourDeep.Dizzle
{
	/// <summary>
	/// DomainModel DizzleDomainModel
	/// Four Deep Dizzle is a DSL for Event Source based DDD with CQRS. It is mainly
	/// built to be used with the Lokad.Cqrs lean implementation.
	/// </summary>
	[DslDesign::DisplayNameResource("FourDeep.Dizzle.DizzleDomainModel.DisplayName", typeof(global::FourDeep.Dizzle.DizzleDomainModel), "FourDeep.Dizzle.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("FourDeep.Dizzle.DizzleDomainModel.Description", typeof(global::FourDeep.Dizzle.DizzleDomainModel), "FourDeep.Dizzle.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("6801bebe-d5cf-456f-a60d-90ac6d4cb888")]
	public partial class DizzleDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DizzleDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x6801bebe, 0xd5cf, 0x456f, 0xa6, 0x0d, 0x90, 0xac, 0x6d, 0x4c, 0xb8, 0x88);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DizzleDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(BoundedContext),
				typeof(AggregateRoot),
				typeof(AggregateState),
				typeof(DomainCommand),
				typeof(Property),
				typeof(View),
				typeof(DomainEvent),
				typeof(Entity),
				typeof(BoundedContextHasAggregateRoot),
				typeof(AggregateRootHasAggregateState),
				typeof(BoundedContextReferencesAggregateState),
				typeof(AggregateRootHandlesDomainCommands),
				typeof(BoundedContextHasDomainCommands),
				typeof(BoundedContextHasProperties),
				typeof(BoundedContextHasViews),
				typeof(BoundedContextHasDomainEvents),
				typeof(AggregateStateSubscribesToDomainEvents),
				typeof(AggregateStateHasProperties),
				typeof(DomainCommandHasProperties),
				typeof(DomainEventHasProperties),
				typeof(EntityHasProperties),
				typeof(BoundedContextHasEntities),
				typeof(ViewHasProperties),
				typeof(ViewHasDomainEvents),
				typeof(DizzleDiagram),
				typeof(CommandConnector),
				typeof(AggregateStateConnector),
				typeof(PropertyConnector),
				typeof(DomainEventConnector),
				typeof(AggregateRootShape),
				typeof(PropertyShape),
				typeof(AggregateStateShape),
				typeof(DomainCommandShape),
				typeof(DomainEventShape),
				typeof(EntityShape),
				typeof(ViewShape),
				typeof(global::FourDeep.Dizzle.FixUpDiagram),
				typeof(global::FourDeep.Dizzle.ConnectorRolePlayerChanged),
				typeof(global::FourDeep.Dizzle.CompartmentItemAddRule),
				typeof(global::FourDeep.Dizzle.CompartmentItemDeleteRule),
				typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerChangeRule),
				typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::FourDeep.Dizzle.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(BoundedContext), "ModelNamespace", BoundedContext.ModelNamespaceDomainPropertyId, typeof(BoundedContext.ModelNamespacePropertyHandler)),
				new DomainMemberInfo(typeof(AggregateRoot), "Name", AggregateRoot.NameDomainPropertyId, typeof(AggregateRoot.NamePropertyHandler)),
				new DomainMemberInfo(typeof(AggregateRoot), "Description", AggregateRoot.DescriptionDomainPropertyId, typeof(AggregateRoot.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateState), "Name", AggregateState.NameDomainPropertyId, typeof(AggregateState.NamePropertyHandler)),
				new DomainMemberInfo(typeof(AggregateState), "Description", AggregateState.DescriptionDomainPropertyId, typeof(AggregateState.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(DomainCommand), "Name", DomainCommand.NameDomainPropertyId, typeof(DomainCommand.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DomainCommand), "Description", DomainCommand.DescriptionDomainPropertyId, typeof(DomainCommand.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Order", Property.OrderDomainPropertyId, typeof(Property.OrderPropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Name", Property.NameDomainPropertyId, typeof(Property.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Type", Property.TypeDomainPropertyId, typeof(Property.TypePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Namespace", Property.NamespaceDomainPropertyId, typeof(Property.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Description", Property.DescriptionDomainPropertyId, typeof(Property.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(View), "Name", View.NameDomainPropertyId, typeof(View.NamePropertyHandler)),
				new DomainMemberInfo(typeof(View), "Description", View.DescriptionDomainPropertyId, typeof(View.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(DomainEvent), "Name", DomainEvent.NameDomainPropertyId, typeof(DomainEvent.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DomainEvent), "Description", DomainEvent.DescriptionDomainPropertyId, typeof(DomainEvent.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "Name", Entity.NameDomainPropertyId, typeof(Entity.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "Description", Entity.DescriptionDomainPropertyId, typeof(Entity.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateRootShape), "FillColor", AggregateRootShape.FillColorDomainPropertyId, typeof(AggregateRootShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateRootShape), "TextColor", AggregateRootShape.TextColorDomainPropertyId, typeof(AggregateRootShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateRootShape), "FillGradientMode", AggregateRootShape.FillGradientModeDomainPropertyId, typeof(AggregateRootShape.FillGradientModePropertyHandler)),
				new DomainMemberInfo(typeof(AggregateStateShape), "FillColor", AggregateStateShape.FillColorDomainPropertyId, typeof(AggregateStateShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateStateShape), "TextColor", AggregateStateShape.TextColorDomainPropertyId, typeof(AggregateStateShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(AggregateStateShape), "FillGradientMode", AggregateStateShape.FillGradientModeDomainPropertyId, typeof(AggregateStateShape.FillGradientModePropertyHandler)),
				new DomainMemberInfo(typeof(DomainCommandShape), "FillColor", DomainCommandShape.FillColorDomainPropertyId, typeof(DomainCommandShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(DomainCommandShape), "TextColor", DomainCommandShape.TextColorDomainPropertyId, typeof(DomainCommandShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(DomainCommandShape), "FillGradientMode", DomainCommandShape.FillGradientModeDomainPropertyId, typeof(DomainCommandShape.FillGradientModePropertyHandler)),
				new DomainMemberInfo(typeof(DomainEventShape), "FillColor", DomainEventShape.FillColorDomainPropertyId, typeof(DomainEventShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(DomainEventShape), "TextColor", DomainEventShape.TextColorDomainPropertyId, typeof(DomainEventShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(DomainEventShape), "FillGradientMode", DomainEventShape.FillGradientModeDomainPropertyId, typeof(DomainEventShape.FillGradientModePropertyHandler)),
				new DomainMemberInfo(typeof(EntityShape), "FillColor", EntityShape.FillColorDomainPropertyId, typeof(EntityShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(EntityShape), "FillGradientMode", EntityShape.FillGradientModeDomainPropertyId, typeof(EntityShape.FillGradientModePropertyHandler)),
				new DomainMemberInfo(typeof(EntityShape), "TextColor", EntityShape.TextColorDomainPropertyId, typeof(EntityShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(ViewShape), "FillColor", ViewShape.FillColorDomainPropertyId, typeof(ViewShape.FillColorPropertyHandler)),
				new DomainMemberInfo(typeof(ViewShape), "TextColor", ViewShape.TextColorDomainPropertyId, typeof(ViewShape.TextColorPropertyHandler)),
				new DomainMemberInfo(typeof(ViewShape), "FillGradientMode", ViewShape.FillGradientModeDomainPropertyId, typeof(ViewShape.FillGradientModePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(BoundedContextHasAggregateRoot), "BoundedContext", BoundedContextHasAggregateRoot.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasAggregateRoot), "Element", BoundedContextHasAggregateRoot.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateRootHasAggregateState), "AggregateRoot", AggregateRootHasAggregateState.AggregateRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateRootHasAggregateState), "AggregateState", AggregateRootHasAggregateState.AggregateStateDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextReferencesAggregateState), "BoundedContext", BoundedContextReferencesAggregateState.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextReferencesAggregateState), "AggregateState", BoundedContextReferencesAggregateState.AggregateStateDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateRootHandlesDomainCommands), "AggregateRoot", AggregateRootHandlesDomainCommands.AggregateRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateRootHandlesDomainCommands), "DomainCommand", AggregateRootHandlesDomainCommands.DomainCommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasDomainCommands), "BoundedContext", BoundedContextHasDomainCommands.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasDomainCommands), "DomainCommand", BoundedContextHasDomainCommands.DomainCommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasProperties), "BoundedContext", BoundedContextHasProperties.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasProperties), "Property", BoundedContextHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasViews), "BoundedContext", BoundedContextHasViews.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasViews), "View", BoundedContextHasViews.ViewDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasDomainEvents), "BoundedContext", BoundedContextHasDomainEvents.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasDomainEvents), "DomainEvent", BoundedContextHasDomainEvents.DomainEventDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateStateSubscribesToDomainEvents), "AggregateState", AggregateStateSubscribesToDomainEvents.AggregateStateDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateStateSubscribesToDomainEvents), "DomainEvent", AggregateStateSubscribesToDomainEvents.DomainEventDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateStateHasProperties), "AggregateState", AggregateStateHasProperties.AggregateStateDomainRoleId),
				new DomainRolePlayerInfo(typeof(AggregateStateHasProperties), "Property", AggregateStateHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(DomainCommandHasProperties), "DomainCommand", DomainCommandHasProperties.DomainCommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(DomainCommandHasProperties), "Property", DomainCommandHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(DomainEventHasProperties), "DomainEvent", DomainEventHasProperties.DomainEventDomainRoleId),
				new DomainRolePlayerInfo(typeof(DomainEventHasProperties), "Property", DomainEventHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityHasProperties), "Entity", EntityHasProperties.EntityDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityHasProperties), "Property", EntityHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasEntities), "BoundedContext", BoundedContextHasEntities.BoundedContextDomainRoleId),
				new DomainRolePlayerInfo(typeof(BoundedContextHasEntities), "Entity", BoundedContextHasEntities.EntityDomainRoleId),
				new DomainRolePlayerInfo(typeof(ViewHasProperties), "View", ViewHasProperties.ViewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ViewHasProperties), "Property", ViewHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(ViewHasDomainEvents), "View", ViewHasDomainEvents.ViewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ViewHasDomainEvents), "DomainEvent", ViewHasDomainEvents.DomainEventDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(20);
				createElementMap.Add(typeof(BoundedContext), 0);
				createElementMap.Add(typeof(AggregateRoot), 1);
				createElementMap.Add(typeof(AggregateState), 2);
				createElementMap.Add(typeof(DomainCommand), 3);
				createElementMap.Add(typeof(Property), 4);
				createElementMap.Add(typeof(View), 5);
				createElementMap.Add(typeof(DomainEvent), 6);
				createElementMap.Add(typeof(Entity), 7);
				createElementMap.Add(typeof(DizzleDiagram), 8);
				createElementMap.Add(typeof(CommandConnector), 9);
				createElementMap.Add(typeof(AggregateStateConnector), 10);
				createElementMap.Add(typeof(PropertyConnector), 11);
				createElementMap.Add(typeof(DomainEventConnector), 12);
				createElementMap.Add(typeof(AggregateRootShape), 13);
				createElementMap.Add(typeof(PropertyShape), 14);
				createElementMap.Add(typeof(AggregateStateShape), 15);
				createElementMap.Add(typeof(DomainCommandShape), 16);
				createElementMap.Add(typeof(DomainEventShape), 17);
				createElementMap.Add(typeof(EntityShape), 18);
				createElementMap.Add(typeof(ViewShape), 19);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::FourDeep.Dizzle.DizzleDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new BoundedContext(partition, propertyAssignments);
				case 1: return new AggregateRoot(partition, propertyAssignments);
				case 2: return new AggregateState(partition, propertyAssignments);
				case 3: return new DomainCommand(partition, propertyAssignments);
				case 4: return new Property(partition, propertyAssignments);
				case 5: return new View(partition, propertyAssignments);
				case 6: return new DomainEvent(partition, propertyAssignments);
				case 7: return new Entity(partition, propertyAssignments);
				case 8: return new DizzleDiagram(partition, propertyAssignments);
				case 9: return new CommandConnector(partition, propertyAssignments);
				case 10: return new AggregateStateConnector(partition, propertyAssignments);
				case 11: return new PropertyConnector(partition, propertyAssignments);
				case 12: return new DomainEventConnector(partition, propertyAssignments);
				case 13: return new AggregateRootShape(partition, propertyAssignments);
				case 14: return new PropertyShape(partition, propertyAssignments);
				case 15: return new AggregateStateShape(partition, propertyAssignments);
				case 16: return new DomainCommandShape(partition, propertyAssignments);
				case 17: return new DomainEventShape(partition, propertyAssignments);
				case 18: return new EntityShape(partition, propertyAssignments);
				case 19: return new ViewShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(16);
				createElementLinkMap.Add(typeof(BoundedContextHasAggregateRoot), 0);
				createElementLinkMap.Add(typeof(AggregateRootHasAggregateState), 1);
				createElementLinkMap.Add(typeof(BoundedContextReferencesAggregateState), 2);
				createElementLinkMap.Add(typeof(AggregateRootHandlesDomainCommands), 3);
				createElementLinkMap.Add(typeof(BoundedContextHasDomainCommands), 4);
				createElementLinkMap.Add(typeof(BoundedContextHasProperties), 5);
				createElementLinkMap.Add(typeof(BoundedContextHasViews), 6);
				createElementLinkMap.Add(typeof(BoundedContextHasDomainEvents), 7);
				createElementLinkMap.Add(typeof(AggregateStateSubscribesToDomainEvents), 8);
				createElementLinkMap.Add(typeof(AggregateStateHasProperties), 9);
				createElementLinkMap.Add(typeof(DomainCommandHasProperties), 10);
				createElementLinkMap.Add(typeof(DomainEventHasProperties), 11);
				createElementLinkMap.Add(typeof(EntityHasProperties), 12);
				createElementLinkMap.Add(typeof(BoundedContextHasEntities), 13);
				createElementLinkMap.Add(typeof(ViewHasProperties), 14);
				createElementLinkMap.Add(typeof(ViewHasDomainEvents), 15);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::FourDeep.Dizzle.DizzleDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new BoundedContextHasAggregateRoot(partition, roleAssignments, propertyAssignments);
				case 1: return new AggregateRootHasAggregateState(partition, roleAssignments, propertyAssignments);
				case 2: return new BoundedContextReferencesAggregateState(partition, roleAssignments, propertyAssignments);
				case 3: return new AggregateRootHandlesDomainCommands(partition, roleAssignments, propertyAssignments);
				case 4: return new BoundedContextHasDomainCommands(partition, roleAssignments, propertyAssignments);
				case 5: return new BoundedContextHasProperties(partition, roleAssignments, propertyAssignments);
				case 6: return new BoundedContextHasViews(partition, roleAssignments, propertyAssignments);
				case 7: return new BoundedContextHasDomainEvents(partition, roleAssignments, propertyAssignments);
				case 8: return new AggregateStateSubscribesToDomainEvents(partition, roleAssignments, propertyAssignments);
				case 9: return new AggregateStateHasProperties(partition, roleAssignments, propertyAssignments);
				case 10: return new DomainCommandHasProperties(partition, roleAssignments, propertyAssignments);
				case 11: return new DomainEventHasProperties(partition, roleAssignments, propertyAssignments);
				case 12: return new EntityHasProperties(partition, roleAssignments, propertyAssignments);
				case 13: return new BoundedContextHasEntities(partition, roleAssignments, propertyAssignments);
				case 14: return new ViewHasProperties(partition, roleAssignments, propertyAssignments);
				case 15: return new ViewHasDomainEvents(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "FourDeep.Dizzle.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DizzleDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DizzleDomainModel.resourceManager == null)
				{
					DizzleDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DizzleDomainModel).Assembly);
				}
				return DizzleDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DizzleDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DizzleDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DizzleDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DizzleCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DizzleDomainModel.copyClosure = copyFilter;
				}
				return DizzleDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DizzleDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DizzleDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DizzleDomainModel.removeClosure = removeFilter;
				}
				return DizzleDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::FourDeep.Dizzle.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::FourDeep.Dizzle.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DizzleDeleteClosure : DizzleDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DizzleDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DizzleDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DizzleDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasAggregateRoot.ElementDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.AggregateRootHasAggregateState.AggregateStateDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasDomainCommands.DomainCommandDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasViews.ViewDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasDomainEvents.DomainEventDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.AggregateStateHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.DomainCommandHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.DomainEventHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.EntityHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.BoundedContextHasEntities.EntityDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.ViewHasProperties.PropertyDomainRoleId, true);
			DomainRoles.Add(global::FourDeep.Dizzle.ViewHasDomainEvents.DomainEventDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DizzleCopyClosure : DizzleCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DizzleCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DizzleCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DizzleCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

