//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace FourDeep.Dizzle
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class BoundedContext
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateBoundedContextMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Element == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						FourDeep.Dizzle.DizzleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"BoundedContext", "", "Element"),
						"DSL0001", this);
			}
		} // ValidateBoundedContextMultiplicity
	} // class BoundedContext
} // FourDeep.Dizzle

namespace FourDeep.Dizzle
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class AggregateRoot
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateAggregateRootMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.AggregateState == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						FourDeep.Dizzle.DizzleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"AggregateRoot", this.Name, "AggregateState"),
						"DSL0001", this);
			}
		} // ValidateAggregateRootMultiplicity
	} // class AggregateRoot
} // FourDeep.Dizzle

namespace FourDeep.Dizzle
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class AggregateState
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateAggregateStateMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.BoundedContext == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						FourDeep.Dizzle.DizzleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"AggregateState", this.Name, "BoundedContext"),
						"DSL0001", this);
			}
		} // ValidateAggregateStateMultiplicity
	} // class AggregateState
} // FourDeep.Dizzle

	
 