//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourDeep.Dizzle
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "4dizzle";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Dizzle";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"FourDeep";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DizzleDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DizzleCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DizzleExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DizzleCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDizzleExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DizzleCommandSetId), 0x0001);
	
		// Package identifier
		public const string DizzlePackageId = "473d108d-ec11-4cad-9e23-2aa12b6368a2";
		
		// Editor factory identifier
		public const string DizzleEditorFactoryId = "0590481e-b24e-4558-a52b-29fbdc780033";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DizzleModelExplorerToolWindowId = "5144e67c-c7f4-4583-b3dc-97eb7b190cae";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace FourDeep.Dizzle
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DizzleCommandSetId = "cafa5178-2972-4662-91e2-3163bc37c802";
	}
}