//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace FourDeep.Dizzle
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\11.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(DizzleExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(DizzleExplorerToolWindow), Constants.DizzleEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@DizzleToolboxTab;FourDeep.Dizzle.Dsl.dll", "FourDeep.Dizzle.DizzleToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@AggregateRootToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.AggregateRootToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@AggregateRootToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@CommandRelationshipToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.CommandRelationshipToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommandRelationship", 
					"@CommandRelationshipToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@AggregateStateToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.AggregateStateToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AggregateState", 
					"@AggregateStateToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@DomainCommandToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.DomainCommandToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DomainCommand", 
					"@DomainCommandToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@AggregateStateRelationshipToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.AggregateStateRelationshipToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AggregateStateRelationship", 
					"@AggregateStateRelationshipToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@PropertyToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.PropertyToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Property", 
					"@PropertyToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@DomainEventToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.DomainEventToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DomainEvent", 
					"@DomainEventToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@EventRelationshipToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.EventRelationshipToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EventRelationship", 
					"@EventRelationshipToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@ViewToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.ViewToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"View", 
					"@ViewToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("FourDeep.Dizzle.DizzleToolboxTab",
					"@EntityToolboxItem;FourDeep.Dizzle.Dsl.dll", 
					"FourDeep.Dizzle.EntityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entity", 
					"@EntityToolboxBitmap;FourDeep.Dizzle.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(DizzleEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(DizzleEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(DizzleEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"Dizzle", typeof(DizzleEditorFactory))]

	internal abstract partial class DizzlePackageBase : DslShell::ModelingPackage
	{
		protected global::FourDeep.Dizzle.DizzleToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new DizzleEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::FourDeep.Dizzle.DizzleToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			DizzleCommandSet commandSet = new DizzleCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			DizzleClipboardCommandSet clipboardCommandSet = new DizzleClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(DizzleExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace FourDeep.Dizzle
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::FourDeep.Dizzle.DizzleDirectiveProcessor), global::FourDeep.Dizzle.DizzleDirectiveProcessor.DizzleDirectiveProcessorName, "A directive processor that provides access to Dizzle files")]
	[global::System.Runtime.InteropServices.Guid(Constants.DizzlePackageId)]
	internal sealed partial class DizzlePackage : DizzlePackageBase
	{
	}
}